![](./4.png)

### Code for part 3 of Question 5

For math below, refer [PDF](https://github.com/rohinarora/EECE5644-Machine_Learning/blob/master/Hw1/ML_Homework_1.pdf)


In [1]:
import numpy as np

In [2]:
'''

y=Ax+b

User inputs-  N, n, μ, and Σ

N,n>0
μ.shape should be (n,1)
Σ.shape should be (n,n)
Σ should be positive semi definite
'''

N=1000000 # number of samples
n=2 # number of dimensions
μ=[[1],[1]] # mean of desired gaussian. 
Σ=[[2,0],[0,2]] # covariance of desired gaussian



In [3]:
def is_pos_def(x):
    '''
    Function returns true if matrix is positive semi definite
    '''
    return np.all(np.linalg.eigvals(x) >= 0)

In [4]:
# convert lists to numpy objects
μ=np.matrix(μ)
Σ=np.matrix([[2,0],[0,2]])

'''
asserts to make sure code below works
'''

assert(N>0)
assert(n>0)
assert(len(μ.shape)==2)
assert(len(Σ.shape)==2)
assert(n==μ.shape[0])
assert(1==μ.shape[1])
assert(n==Σ.shape[0])
assert(n==Σ.shape[1])
assert(is_pos_def(Σ)==True)

In [5]:
'''Sample from Gaussian of zero mean and unit variance '''
x=np.random.normal(size=(n, N))
print (x.shape)

'''Calculate the affine transform parameters'''
A = np.linalg.cholesky(Σ)
b = μ


'''y is the matrix with desired samples''' 
y=A.dot(x)+b

(2, 1000000)


In [9]:
'''
sanity check
'''

print ("mean of y is \n{}".format(y.mean(1)))
print ("\ndesired mean is \n{}".format(μ))
print ("\n\ncovariance matrix of y is \n{}".format(np.cov(y)))
print ("\ndesired covariance matrix is \n{}".format(Σ))

print ("\n\n\nThe mean and covariance of samples obtained match the mean and covariance input by the user")

mean of y is 
[[0.99911052]
 [1.00011709]]

desired mean is 
[[1]
 [1]]


covariance matrix of y is 
[[2.00614275e+00 1.99908905e-03]
 [1.99908905e-03 2.00158759e+00]]

desired covariance matrix is 
[[2 0]
 [0 2]]



The mean and covariance of samples obtained match the mean and covariance input by the user
